---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

`tinyjs` - R pkg wrapper to <https://github.com/gfwilliams/tiny-js>

The following functions are implemented:

- `init`
- `exec`
- `get`

The following data sets are included:

### News

- Version 0.1.0.9000 released

### Installation

```{r eval=FALSE}
devtools::install_github("brudis-r7/tinyjs")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
options(width=120)
```

### Usage

```{r}
library(tinyjs)

# current verison
packageVersion("tinyjs")

library(tinyjs)

init()

exec("var a=10;")
get("a")

exec("var b={this:'that', or:4, the:['ot', 'he', 'r']};")
get("b")
```

### Test Results

```{r}
library(tinyjs)
library(testthat)

date()

test_dir("tests/")
```

### Code of Conduct

Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). 
By participating in this project you agree to abide by its terms.
