// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// init
void init();
RcppExport SEXP tinyjs_init() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    init();
    return R_NilValue;
END_RCPP
}
// exec
void exec(std::string buffer);
RcppExport SEXP tinyjs_exec(SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type buffer(bufferSEXP);
    exec(buffer);
    return R_NilValue;
END_RCPP
}
// get
std::string get(std::string param);
RcppExport SEXP tinyjs_get(SEXP paramSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type param(paramSEXP);
    __result = Rcpp::wrap(get(param));
    return __result;
END_RCPP
}
