# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_ctx_init <- function() {
    invisible(.Call('tinyjs_rcpp_ctx_init', PACKAGE = 'tinyjs'))
}

rcpp_ctx_exec <- function(buffer) {
    invisible(.Call('tinyjs_rcpp_ctx_exec', PACKAGE = 'tinyjs', buffer))
}

rcpp_get <- function(param) {
    .Call('tinyjs_rcpp_get', PACKAGE = 'tinyjs', param)
}

